export const FETCH_USER_DETAILS = 'FET_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SHOW_POPUP = 'SHOW_POPUP';
export const SHOW_LOADER = 'SHOW_LOADER';
export const FETCH_TASKS = 'FETCH_TASKS';
