export const FETCH_USER_DETAILS = 'FET_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SHOW_POPUP = 'SHOW_POPUP';
export const SHOW_LOADER = 'SHOW_LOADER';
export const FETCH_TASKS = 'FETCH_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_SHOW_CREATE_TASK_MODAL= 'SET_SHOW_CREATE_TASK_MODAL';
export const SET_SHOW_QUICK_ACTIONS_TASK_MODAL= 'SET_SHOW_QUICK_ACTIONS_TASK_MODAL';
export const SEARCH_USER = 'SEARCH_USER';
export const SHOW_SEARCHED_USER_PROFILE_MODAL = 'SHOW_SEARCHED_USER_PROFILE_MODAL';

