export default {
    ICON_EMAIL: 'mail-outline',
    ICON_PASSWORD: 'lock-closed-outline',
    ICON_NAME: 'person-outline',
    ICON_TASK_STATUS: 'checkmark-done-outline',
    ICON_BACK_BUTTON: 'arrow-back-outline',
    ICON_NOTIFICATION: 'notifications-outline',
    ICON_HOME: 'home-outline',
    ICON_ADD: 'add-circle-outline',
    ICON_PROFILE: 'people-outline',
    ICON_CREATE: 'add-circle-outline',
    ICON_SETTINGS: 'settings-outline',
    ICON_TASKS: 'newspaper-outline',
    ICON_SEARCH: 'search-outline',
    ICON_TRASH: 'trash-outline',
    ICON_INFO:'information-outline',
    ICON_TASK_DONE: 'checkmark-done-outline',
    ICON_UPLOAD: 'cloud-upload-outline',
    ICON_EDIT: 'create-outline',
    ICON_CLOSE: 'close-outline',
    ICON_SUB_TASKS: 'albums-outline',
};
