export default {
    ENTRY_TITLE : 'Organize\nyour day easily!',
    ENTRY_SUBTITLE: 'Planning the daily work, it has never been so impacting',
    START_BUTTON: 'Start',
    SIGN_UP_BUTTON: 'Create Account',
    HAVE_ACCOUNT: 'Do You have an account?',
    LOGIN: 'Login',
    LOGIN_SCREEN_TITLE: 'Welcome back, Lets login you!',
    SIGN_UP_SCREEN_TITLE: 'Welcome, Lets create account!',
    PLACEHOLDER_EMAIL: 'Email',
    PLACEHOLDER_PASSWORD: 'Password',
    PLACEHOLDER_NAME: 'Your name?',
    PLACEHOLDER_REPEAT_PASSWORD: 'Repeat password',
    PLACEHOLDER_SUB_TASK: 'Sub task',
    PLACEHOLDER_TITLE: 'Title',
    FORGOT_PASSWORD: 'Forgot password?',
    CREATE: 'Create',
    SELECT_END_DATE: 'Please choose end date',
    SAVE: 'Save',
    PLEASE_UPLOAD_AVATAR: 'Please upload your avatar.',
};
